"""
12-week, 84-day training plan fixture. Sourced from Matthew's Weekly Fitness Plan
spreadsheet (SGPT 365 phase structure). This is read-only data; the app only writes
workout logs, never this fixture.
"""

PLAN = [
    # ── Week 1 ────────────────────────────────────────────────────────────────
    {
        "day_index": 0, "week": 1, "day_of_week": "Mon", "label": "Wk 1 - Mon",
        "focus": "Lower Strength", "day_type": "lift",
        "strength": "A. Back Squat 4x6 @ ~65% 1RM (or RPE 7).\nB. Romanian Deadlift 3x8.\nC. Walking Lunge 3x12 each leg (DBs).\nD. Hanging Leg Raise 3x10 + Plank 3x45s.\nWarm up 5 min bike + dynamic stretch.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 1, "week": 1, "day_of_week": "Tue", "label": "Wk 1 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional core: 3 rounds: 20 sit-ups, 20 flutter kicks, 30s plank.",
        "run": "Easy 3.0 mi @ 9:45-10:30/mi. Conversational. 5 min walk + stretch after.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 2, "week": 1, "day_of_week": "Wed", "label": "Wk 1 - Wed",
        "focus": "Upper Push", "day_type": "lift",
        "strength": "A. DB Bench Press 4x6-8 (~65% of working max).\nB. Standing Overhead Press 3x6.\nC. Incline DB Press 3x10.\nD. Triceps Pushdown 3x12 + Lateral Raise 3x12.\nFinisher: 50 push-ups for time (break as needed).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 3, "week": 1, "day_of_week": "Thu", "label": "Wk 1 - Thu",
        "focus": "Tempo Run", "day_type": "run",
        "strength": "Optional after: 3 rounds: 10 pull-ups, 20 push-ups, 30 air squats.",
        "run": "1 mi easy WU.\nTempo: 2.0 mi @ 8:45/mi.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 4, "week": 1, "day_of_week": "Fri", "label": "Wk 1 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 5 sets at 60% of max reps each set.\nB. Barbell Row 4x6-8.\nC. Single-arm DB Row 3x10 each.\nD. Farmer Carry 3x40m heavy.\nE. Face Pulls 3x15.\nCool down: dead hang 2x30s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 5, "week": 1, "day_of_week": "Sat", "label": "Wk 1 - Sat",
        "focus": "Long Run", "day_type": "run",
        "strength": "None. Save the legs.",
        "run": "Long run: 5.0 mi @ 10:00-10:30/mi.\nRun by feel. Walk 5 min after, full top-to-bottom stretch.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 6, "week": 1, "day_of_week": "Sun", "label": "Wk 1 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "Pick one: 30-45 min easy walk, yoga flow, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 2 ────────────────────────────────────────────────────────────────
    {
        "day_index": 7, "week": 2, "day_of_week": "Mon", "label": "Wk 2 - Mon",
        "focus": "Lower Strength", "day_type": "lift",
        "strength": "A. Back Squat 4x6 @ ~70% 1RM (or RPE 7).\nB. Romanian Deadlift 3x8.\nC. Walking Lunge 3x12 each leg (DBs).\nD. Hanging Leg Raise 3x10 + Plank 3x45s.\nWarm up 5 min bike + dynamic stretch.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 8, "week": 2, "day_of_week": "Tue", "label": "Wk 2 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional core: 3 rounds: 20 sit-ups, 20 flutter kicks, 30s plank.",
        "run": "Easy 3.5 mi @ 9:45-10:30/mi. Conversational. 5 min walk + stretch after.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 9, "week": 2, "day_of_week": "Wed", "label": "Wk 2 - Wed",
        "focus": "Upper Push", "day_type": "lift",
        "strength": "A. DB Bench Press 4x6-8 (~70% of working max).\nB. Standing Overhead Press 3x6.\nC. Incline DB Press 3x10.\nD. Triceps Pushdown 3x12 + Lateral Raise 3x12.\nFinisher: 50 push-ups for time (break as needed).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 10, "week": 2, "day_of_week": "Thu", "label": "Wk 2 - Thu",
        "focus": "Tempo Run", "day_type": "run",
        "strength": "Optional after: 3 rounds: 10 pull-ups, 20 push-ups, 30 air squats.",
        "run": "1 mi easy WU.\nTempo: 2.0 mi @ 8:35/mi.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 11, "week": 2, "day_of_week": "Fri", "label": "Wk 2 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 5 sets at 65% of max reps each set.\nB. Barbell Row 4x6-8.\nC. Single-arm DB Row 3x10 each.\nD. Farmer Carry 3x40m heavy.\nE. Face Pulls 3x15.\nCool down: dead hang 2x30s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 12, "week": 2, "day_of_week": "Sat", "label": "Wk 2 - Sat",
        "focus": "Long Run", "day_type": "run",
        "strength": "None. Save the legs.",
        "run": "Long run: 5.5 mi @ 10:00-10:30/mi.\nRun by feel. Walk 5 min after, full top-to-bottom stretch.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 13, "week": 2, "day_of_week": "Sun", "label": "Wk 2 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "Pick one: 30-45 min easy walk, yoga flow, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 3 ────────────────────────────────────────────────────────────────
    {
        "day_index": 14, "week": 3, "day_of_week": "Mon", "label": "Wk 3 - Mon",
        "focus": "Lower Strength", "day_type": "lift",
        "strength": "A. Back Squat 5x5 @ ~72% 1RM (or RPE 7).\nB. Romanian Deadlift 3x8.\nC. Walking Lunge 3x12 each leg (DBs).\nD. Hanging Leg Raise 3x10 + Plank 3x45s.\nWarm up 5 min bike + dynamic stretch.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 15, "week": 3, "day_of_week": "Tue", "label": "Wk 3 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional core: 3 rounds: 20 sit-ups, 20 flutter kicks, 30s plank.",
        "run": "Easy 4.0 mi @ 9:45-10:30/mi. Conversational. 5 min walk + stretch after.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 16, "week": 3, "day_of_week": "Wed", "label": "Wk 3 - Wed",
        "focus": "Upper Push", "day_type": "lift",
        "strength": "A. DB Bench Press 5x5 (~72% of working max).\nB. Standing Overhead Press 3x6.\nC. Incline DB Press 3x10.\nD. Triceps Pushdown 3x12 + Lateral Raise 3x12. Add Dips 3x8.\nFinisher: 50 push-ups for time (break as needed).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 17, "week": 3, "day_of_week": "Thu", "label": "Wk 3 - Thu",
        "focus": "Tempo Run", "day_type": "run",
        "strength": "Optional after: 3 rounds: 10 pull-ups, 20 push-ups, 30 air squats.",
        "run": "1 mi easy WU.\nTempo: 2.5 mi @ 8:30/mi.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 18, "week": 3, "day_of_week": "Fri", "label": "Wk 3 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 5 sets at 70% of max reps each set.\nB. Barbell Row 5x5.\nC. Single-arm DB Row 3x10 each.\nD. Farmer Carry 3x40m heavy.\nE. Face Pulls 3x15.\nCool down: dead hang 2x30s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 19, "week": 3, "day_of_week": "Sat", "label": "Wk 3 - Sat",
        "focus": "Long Run", "day_type": "run",
        "strength": "None. Save the legs.",
        "run": "Long run: 6.0 mi @ 10:00-10:30/mi.\nRun by feel. Walk 5 min after, full top-to-bottom stretch.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 20, "week": 3, "day_of_week": "Sun", "label": "Wk 3 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "Pick one: 30-45 min easy walk, yoga flow, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 4 ────────────────────────────────────────────────────────────────
    {
        "day_index": 21, "week": 4, "day_of_week": "Mon", "label": "Wk 4 - Mon",
        "focus": "Lower Strength", "day_type": "lift",
        "strength": "A. Back Squat 5x5 @ ~75% 1RM (or RPE 7).\nB. Romanian Deadlift 3x8.\nC. Walking Lunge 3x12 each leg (DBs).\nD. Hanging Leg Raise 3x10 + Plank 3x45s.\nWarm up 5 min bike + dynamic stretch.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 22, "week": 4, "day_of_week": "Tue", "label": "Wk 4 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional core: 3 rounds: 20 sit-ups, 20 flutter kicks, 30s plank.",
        "run": "Easy 3.0 mi @ 9:45-10:30/mi. Conversational. 5 min walk + stretch after.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 23, "week": 4, "day_of_week": "Wed", "label": "Wk 4 - Wed",
        "focus": "Upper Push", "day_type": "lift",
        "strength": "A. DB Bench Press 5x5 (~75% of working max).\nB. Standing Overhead Press 3x6.\nC. Incline DB Press 3x10.\nD. Triceps Pushdown 3x12 + Lateral Raise 3x12. Add Dips 3x8.\nFinisher: 50 push-ups for time (break as needed).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 24, "week": 4, "day_of_week": "Thu", "label": "Wk 4 - Thu",
        "focus": "2-Mile Test", "day_type": "test",
        "strength": "Save it for the run. No lift.",
        "run": "TEST: 1 mi WU easy, then 2 mi time trial AFAP. 1 mi CD jog.\nGoal: beat your 18:00. Log the time.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 25, "week": 4, "day_of_week": "Fri", "label": "Wk 4 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 5 sets at 75% of max reps each set.\nB. Barbell Row 5x5.\nC. Single-arm DB Row 3x10 each.\nD. Farmer Carry 3x40m heavy.\nE. Face Pulls 3x15.\nCool down: dead hang 2x30s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 26, "week": 4, "day_of_week": "Sat", "label": "Wk 4 - Sat",
        "focus": "Long Run", "day_type": "run",
        "strength": "None. Save the legs.",
        "run": "Long run: 5.0 mi @ 10:00-10:30/mi.\nRun by feel. Walk 5 min after, full top-to-bottom stretch.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 27, "week": 4, "day_of_week": "Sun", "label": "Wk 4 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "Pick one: 30-45 min easy walk, yoga flow, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 5 ─ Phase 2: Power + Speed ──────────────────────────────────────
    {
        "day_index": 28, "week": 5, "day_of_week": "Mon", "label": "Wk 5 - Mon",
        "focus": "Lower Strength + Plyo", "day_type": "lift",
        "strength": "A. Back Squat 4x4 @ ~80% 1RM.\nB. Romanian Deadlift 3x6 (heavier than Phase 1).\nC. Box Jumps 3x5 (max effort, full reset between reps).\nD. Hanging Leg Raise 3x10 + Plank 3x60s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 29, "week": 5, "day_of_week": "Tue", "label": "Wk 5 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional 5-min mobility flow.",
        "run": "Easy 3.5 mi @ 9:30-10:15/mi. Conversational pace, recovery focus.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 30, "week": 5, "day_of_week": "Wed", "label": "Wk 5 - Wed",
        "focus": "Upper Push + Power", "day_type": "lift",
        "strength": "A. DB Bench Press 4x4 (~80% of working max).\nB. Standing Overhead Press 4x4.\nC. Push Press 3x5 (explosive on the leg drive).\nD. Incline DB Press 3x8.\nFinisher: Med-ball Slams 3x10 (or Burpees 3x10 if no ball).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 31, "week": 5, "day_of_week": "Thu", "label": "Wk 5 - Thu",
        "focus": "Speed Intervals", "day_type": "run",
        "strength": "Save it for the run.",
        "run": "1 mi easy WU.\n4 x 400m @ 6:45/mi pace, 90s walking rest between.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 32, "week": 5, "day_of_week": "Fri", "label": "Wk 5 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 4x4 weighted (add 10-25 lb if possible).\nB. Barbell Row 4x4.\nC. Single-arm DB Row 3x8 each (heavier).\nD. Farmer Carry 3x40m heavy.\nE. Broad Jumps 3x5 (full reset).\nF. Face Pulls 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 33, "week": 5, "day_of_week": "Sat", "label": "Wk 5 - Sat",
        "focus": "Long Run", "day_type": "run",
        "strength": "None. Save the legs.",
        "run": "Long run: 6.0 mi.\nFirst 80% at 10:00-10:15/mi, last mile at 9:15-9:30/mi (fast finish).",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 34, "week": 5, "day_of_week": "Sun", "label": "Wk 5 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30-45 min easy walk, yoga, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 6 ────────────────────────────────────────────────────────────────
    {
        "day_index": 35, "week": 6, "day_of_week": "Mon", "label": "Wk 6 - Mon",
        "focus": "Lower Strength + Plyo", "day_type": "lift",
        "strength": "A. Back Squat 4x4 @ ~82% 1RM.\nB. Romanian Deadlift 3x6 (heavier than Phase 1).\nC. Box Jumps 3x5 (max effort, full reset between reps).\nD. Hanging Leg Raise 3x10 + Plank 3x60s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 36, "week": 6, "day_of_week": "Tue", "label": "Wk 6 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional 5-min mobility flow.",
        "run": "Easy 4.0 mi @ 9:30-10:15/mi. Conversational pace, recovery focus.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 37, "week": 6, "day_of_week": "Wed", "label": "Wk 6 - Wed",
        "focus": "Upper Push + Power", "day_type": "lift",
        "strength": "A. DB Bench Press 4x4 (~82% of working max).\nB. Standing Overhead Press 4x4.\nC. Push Press 3x5 (explosive on the leg drive).\nD. Incline DB Press 3x8.\nFinisher: Med-ball Slams 3x10 (or Burpees 3x10 if no ball).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 38, "week": 6, "day_of_week": "Thu", "label": "Wk 6 - Thu",
        "focus": "Speed Intervals", "day_type": "run",
        "strength": "Save it for the run.",
        "run": "1 mi easy WU.\n5 x 400m @ 6:30/mi pace, 90s walking rest.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 39, "week": 6, "day_of_week": "Fri", "label": "Wk 6 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 4x4 weighted (add 10-25 lb if possible).\nB. Barbell Row 4x4.\nC. Single-arm DB Row 3x8 each (heavier).\nD. Farmer Carry 3x40m heavy.\nE. Broad Jumps 3x5 (full reset).\nF. Face Pulls 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 40, "week": 6, "day_of_week": "Sat", "label": "Wk 6 - Sat",
        "focus": "Long Run", "day_type": "run",
        "strength": "None. Save the legs.",
        "run": "Long run: 6.5 mi.\nFirst 80% at 10:00-10:15/mi, last mile at 9:15-9:30/mi (fast finish).",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 41, "week": 6, "day_of_week": "Sun", "label": "Wk 6 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30-45 min easy walk, yoga, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 7 ────────────────────────────────────────────────────────────────
    {
        "day_index": 42, "week": 7, "day_of_week": "Mon", "label": "Wk 7 - Mon",
        "focus": "Lower Strength + Plyo", "day_type": "lift",
        "strength": "A. Back Squat 5x3 @ ~85% 1RM.\nB. Romanian Deadlift 3x6 (heavier than Phase 1).\nC. Box Jumps 3x5 (max effort, full reset between reps).\nD. Hanging Leg Raise 3x10 + Plank 3x60s.\nE. KB Swings 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 43, "week": 7, "day_of_week": "Tue", "label": "Wk 7 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional 5-min mobility flow.",
        "run": "Easy 4.0 mi @ 9:30-10:15/mi. Conversational pace, recovery focus.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 44, "week": 7, "day_of_week": "Wed", "label": "Wk 7 - Wed",
        "focus": "Upper Push + Power", "day_type": "lift",
        "strength": "A. DB Bench Press 5x3 (~85% of working max).\nB. Standing Overhead Press 4x4.\nC. Push Press 3x5 (explosive on the leg drive).\nD. Incline DB Press 3x8.\nFinisher: Med-ball Slams 3x10 (or Burpees 3x10 if no ball).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 45, "week": 7, "day_of_week": "Thu", "label": "Wk 7 - Thu",
        "focus": "Speed Intervals", "day_type": "run",
        "strength": "Save it for the run.",
        "run": "1 mi easy WU.\n6 x 400m @ 6:30/mi pace, 90s walking rest.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 46, "week": 7, "day_of_week": "Fri", "label": "Wk 7 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 5x3 weighted (add 10-25 lb if possible).\nB. Barbell Row 5x3.\nC. Single-arm DB Row 3x8 each (heavier).\nD. Farmer Carry 3x40m heavy.\nE. Broad Jumps 3x5 (full reset).\nF. Face Pulls 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 47, "week": 7, "day_of_week": "Sat", "label": "Wk 7 - Sat",
        "focus": "Long Run", "day_type": "run",
        "strength": "None. Save the legs.",
        "run": "Long run: 7.0 mi.\nFirst 80% at 10:00-10:15/mi, last mile at 9:15-9:30/mi (fast finish).",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 48, "week": 7, "day_of_week": "Sun", "label": "Wk 7 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30-45 min easy walk, yoga, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 8 ────────────────────────────────────────────────────────────────
    {
        "day_index": 49, "week": 8, "day_of_week": "Mon", "label": "Wk 8 - Mon",
        "focus": "Lower Strength + Plyo", "day_type": "lift",
        "strength": "A. Back Squat 4x4 @ ~80% 1RM.\nB. Romanian Deadlift 3x6 (heavier than Phase 1).\nC. Box Jumps 3x5 (max effort, full reset between reps).\nD. Hanging Leg Raise 3x10 + Plank 3x60s.\nE. KB Swings 3x12.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 50, "week": 8, "day_of_week": "Tue", "label": "Wk 8 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional 5-min mobility flow.",
        "run": "Easy 3.0 mi @ 9:30-10:15/mi. Conversational pace, recovery focus.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 51, "week": 8, "day_of_week": "Wed", "label": "Wk 8 - Wed",
        "focus": "Upper Push + Power", "day_type": "lift",
        "strength": "A. DB Bench Press 4x4 (~80% of working max).\nB. Standing Overhead Press 4x4.\nC. Push Press 3x5 (explosive on the leg drive).\nD. Incline DB Press 3x8.\nFinisher: Med-ball Slams 3x10 (or Burpees 3x10 if no ball).",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 52, "week": 8, "day_of_week": "Thu", "label": "Wk 8 - Thu",
        "focus": "Speed Intervals", "day_type": "run",
        "strength": "Save it for the run.",
        "run": "1 mi easy WU.\n4 x 800m @ 7:00/mi pace, 2 min walking rest between.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 53, "week": 8, "day_of_week": "Fri", "label": "Wk 8 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 4x4 weighted (add 10-25 lb if possible).\nB. Barbell Row 4x4.\nC. Single-arm DB Row 3x8 each (heavier).\nD. Farmer Carry 3x40m heavy.\nE. Broad Jumps 3x5 (full reset).\nF. Face Pulls 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 54, "week": 8, "day_of_week": "Sat", "label": "Wk 8 - Sat",
        "focus": "5-Mile Test", "day_type": "test",
        "strength": "None. Save the legs.",
        "run": "TEST: 5-mile run at goal effort.\nTarget: under 50:00 (10:00/mi). Compare to your 52:00 baseline.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 55, "week": 8, "day_of_week": "Sun", "label": "Wk 8 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30-45 min easy walk, yoga, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 9 ─ Phase 3: Endurance + Capacity ────────────────────────────────
    {
        "day_index": 56, "week": 9, "day_of_week": "Mon", "label": "Wk 9 - Mon",
        "focus": "Lower Maintenance + Conditioning", "day_type": "lift",
        "strength": "A. Back Squat 3x5 @ ~75% (maintenance).\nB. Romanian Deadlift 3x6.\nC. Conditioning circuit, 3 rounds: 15 KB swings, 15 box jumps, 15 push-ups.\nD. Plank 3x60s + Side Plank 2x30s each.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 57, "week": 9, "day_of_week": "Tue", "label": "Wk 9 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional 5-min mobility.",
        "run": "Easy 4.5 mi @ 9:45-10:15/mi. Stay aerobic, build the base.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 58, "week": 9, "day_of_week": "Wed", "label": "Wk 9 - Wed",
        "focus": "Upper Push + Conditioning", "day_type": "lift",
        "strength": "A. DB Bench Press 3x5 @ ~75%.\nB. Standing Overhead Press 3x5.\nC. Incline DB Press 3x8.\nD. Conditioning: 4 rounds: 10 push-ups, 10 air squats, 200m run.\nE. Triceps Pushdown 3x12.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 59, "week": 9, "day_of_week": "Thu", "label": "Wk 9 - Thu",
        "focus": "Tempo Run", "day_type": "run",
        "strength": "Save it for the run.",
        "run": "1 mi easy WU.\nTempo: 3.0 mi @ 8:25-8:35/mi.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 60, "week": 9, "day_of_week": "Fri", "label": "Wk 9 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 3 sets at ~70% of max each set.\nB. Barbell Row 3x5 @ ~75%.\nC. Single-arm DB Row 3x8 each.\nD. Farmer Carry 3x50m heavy.\nE. Face Pulls 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 61, "week": 9, "day_of_week": "Sat", "label": "Wk 9 - Sat",
        "focus": "Long Run with Fast Finish", "day_type": "run",
        "strength": "None.",
        "run": "Long run: 7.0 mi.\nFirst 6 mi at 10:00-10:15/mi, last mile at 9:00-9:15/mi.\nHard finish, easy walk after.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 62, "week": 9, "day_of_week": "Sun", "label": "Wk 9 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30-45 min easy walk, yoga, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 10 ───────────────────────────────────────────────────────────────
    {
        "day_index": 63, "week": 10, "day_of_week": "Mon", "label": "Wk 10 - Mon",
        "focus": "Lower Maintenance + Conditioning", "day_type": "lift",
        "strength": "A. Back Squat 3x5 @ ~75% (maintenance).\nB. Romanian Deadlift 3x6.\nC. Conditioning circuit, 3 rounds: 15 KB swings, 15 box jumps, 15 push-ups.\nD. Plank 3x60s + Side Plank 2x30s each.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 64, "week": 10, "day_of_week": "Tue", "label": "Wk 10 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional 5-min mobility.",
        "run": "Easy 5.0 mi @ 9:45-10:15/mi. Stay aerobic, build the base.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 65, "week": 10, "day_of_week": "Wed", "label": "Wk 10 - Wed",
        "focus": "Upper Push + Conditioning", "day_type": "lift",
        "strength": "A. DB Bench Press 3x5 @ ~75%.\nB. Standing Overhead Press 3x5.\nC. Incline DB Press 3x8.\nD. Conditioning: 4 rounds: 10 push-ups, 10 air squats, 200m run.\nE. Triceps Pushdown 3x12.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 66, "week": 10, "day_of_week": "Thu", "label": "Wk 10 - Thu",
        "focus": "Tempo Run", "day_type": "run",
        "strength": "Save it for the run.",
        "run": "1 mi easy WU.\nTempo: 3.0 mi @ 8:25-8:35/mi.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 67, "week": 10, "day_of_week": "Fri", "label": "Wk 10 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 3 sets at ~70% of max each set.\nB. Barbell Row 3x5 @ ~75%.\nC. Single-arm DB Row 3x8 each.\nD. Farmer Carry 3x50m heavy.\nE. Face Pulls 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 68, "week": 10, "day_of_week": "Sat", "label": "Wk 10 - Sat",
        "focus": "Long Run with Fast Finish", "day_type": "run",
        "strength": "None.",
        "run": "Long run: 7.5 mi.\nFirst 6.5 mi at 10:00-10:15/mi, last mile at 9:00-9:15/mi.\nHard finish, easy walk after.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 69, "week": 10, "day_of_week": "Sun", "label": "Wk 10 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30-45 min easy walk, yoga, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 11 ───────────────────────────────────────────────────────────────
    {
        "day_index": 70, "week": 11, "day_of_week": "Mon", "label": "Wk 11 - Mon",
        "focus": "Lower Maintenance + Conditioning", "day_type": "lift",
        "strength": "A. Back Squat 3x5 @ ~75% (maintenance).\nB. Romanian Deadlift 3x6.\nC. Conditioning circuit, 3 rounds: 15 KB swings, 15 box jumps, 15 push-ups.\nD. Plank 3x60s + Side Plank 2x30s each.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from last week. Foam roll quads/glutes 5 min. Bed by 10 PM.",
    },
    {
        "day_index": 71, "week": 11, "day_of_week": "Tue", "label": "Wk 11 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "Optional 5-min mobility.",
        "run": "Easy 5.0 mi @ 9:45-10:15/mi. Stay aerobic, build the base.",
        "mental_recovery": "Mental: pick one affirmation to repeat on the run. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 72, "week": 11, "day_of_week": "Wed", "label": "Wk 11 - Wed",
        "focus": "Upper Push + Conditioning", "day_type": "lift",
        "strength": "A. DB Bench Press 3x5 @ ~75%.\nB. Standing Overhead Press 3x5.\nC. Incline DB Press 3x8.\nD. Conditioning: 4 rounds: 10 push-ups, 10 air squats, 200m run.\nE. Triceps Pushdown 3x12.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Band shoulder dislocates 2x10.",
    },
    {
        "day_index": 73, "week": 11, "day_of_week": "Thu", "label": "Wk 11 - Thu",
        "focus": "Tempo Run", "day_type": "run",
        "strength": "Save it for the run.",
        "run": "1 mi easy WU.\nTempo: 3.5 mi @ 8:25-8:35/mi.\n1 mi easy CD.",
        "mental_recovery": "Mental: journal one paragraph after the run. Electrolytes after.",
    },
    {
        "day_index": 74, "week": 11, "day_of_week": "Fri", "label": "Wk 11 - Fri",
        "focus": "Upper Pull + Carry", "day_type": "lift",
        "strength": "A. Pull-ups: 3 sets at ~70% of max each set.\nB. Barbell Row 3x5 @ ~75%.\nC. Single-arm DB Row 3x8 each.\nD. Farmer Carry 3x50m heavy.\nE. Face Pulls 3x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: read 10 pages of a non-screen book. T-spine mobility 5 min.",
    },
    {
        "day_index": 75, "week": 11, "day_of_week": "Sat", "label": "Wk 11 - Sat",
        "focus": "Long Run with Fast Finish", "day_type": "run",
        "strength": "None.",
        "run": "Long run: 8.0 mi.\nFirst 7 mi at 10:00-10:15/mi, last mile at 9:00-9:15/mi.\nHard finish, easy walk after.",
        "mental_recovery": "Mental: pick one tough moment in the run, stay positive. Big post-run meal.",
    },
    {
        "day_index": 76, "week": 11, "day_of_week": "Sun", "label": "Wk 11 - Sun",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30-45 min easy walk, yoga, or light bike.",
        "run": "No structured run.",
        "mental_recovery": "Plan the week: meals prepped, gym bag packed, routes chosen. Bed by 10 PM.",
    },
    # ── Week 12 ─ Deload + Retest ─────────────────────────────────────────────
    {
        "day_index": 77, "week": 12, "day_of_week": "Mon", "label": "Wk 12 - Mon",
        "focus": "Lower Deload", "day_type": "lift",
        "strength": "A. Back Squat 2x5 @ ~60% — focus on movement quality, no grinding.\nB. Romanian Deadlift 2x6, light.\nC. Plank 2x60s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: write 3 wins from the entire 12 weeks. Foam roll full body 10 min. Bed by 10 PM.",
    },
    {
        "day_index": 78, "week": 12, "day_of_week": "Tue", "label": "Wk 12 - Tue",
        "focus": "Easy Run", "day_type": "run",
        "strength": "None.",
        "run": "Easy 3.0 mi @ 9:30-10:30/mi. Shake out the legs, stay conversational.",
        "mental_recovery": "Mental: visualize the retest on Sunday. Hydrate hard (~100 oz).",
    },
    {
        "day_index": 79, "week": 12, "day_of_week": "Wed", "label": "Wk 12 - Wed",
        "focus": "Upper Push Deload", "day_type": "lift",
        "strength": "A. DB Bench Press 2x5 @ ~60% — light, crisp reps.\nB. Standing Overhead Press 2x5.\nC. Face Pulls 2x15.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: 5 min box breathing before bed. Shoulder mobility 5 min.",
    },
    {
        "day_index": 80, "week": 12, "day_of_week": "Thu", "label": "Wk 12 - Thu",
        "focus": "Active Recovery", "day_type": "rest",
        "strength": "30 min easy walk or yoga. No intensity.",
        "run": "No structured run.",
        "mental_recovery": "Mental: journal — what improved over 12 weeks? What will you do differently next cycle?",
    },
    {
        "day_index": 81, "week": 12, "day_of_week": "Fri", "label": "Wk 12 - Fri",
        "focus": "Upper Pull Deload", "day_type": "lift",
        "strength": "A. Pull-ups: 2 sets, easy — stop well short of failure.\nB. Barbell Row 2x5 @ ~60%.\nC. Dead hang 1x30s.",
        "run": "Rest from running.",
        "mental_recovery": "Mental: rest up — the retest is tomorrow. Early bed.",
    },
    {
        "day_index": 82, "week": 12, "day_of_week": "Sat", "label": "Wk 12 - Sat",
        "focus": "Easy Run", "day_type": "run",
        "strength": "None.",
        "run": "Easy 3.0 mi — just keep the legs loose. No effort.",
        "mental_recovery": "Mental: tomorrow is the retest. Big meal tonight, hydrate all day.",
    },
    {
        "day_index": 83, "week": 12, "day_of_week": "Sun", "label": "Wk 12 - Sun",
        "focus": "2-Mile Retest", "day_type": "test",
        "strength": "None. Save everything for the run.",
        "run": "RETEST: 1 mi easy WU, then 2 mi time trial AFAP, 1 mi easy CD.\nCompare to Week 4 result. How much did you improve?",
        "mental_recovery": "Mental: celebrate the finish — you did the work. Log your time and plan the next cycle.",
    },
]

assert len(PLAN) == 84, f"Plan has {len(PLAN)} days, expected 84"
