// Add a new tile by appending to this list. Each entry renders as a card on the
// dashboard. The dashboard does not import or run app code; it just links out.
window.APPS = [
  {
    id: "meal-planner",
    title: "Meal Planner",
    desc: "Recipes, weekly plans, and grocery lists.",
    icon: "🍳",
    href: "/apps/meal-planner/",
    enabled: true,
  },
  {
    id: "budget",
    title: "Budget Tracker",
    desc: "Monthly budget, surplus allocation, and retirement balances.",
    icon: "💰",
    href: "/apps/budget/",
    enabled: true,
  },
  {
    id: "fitness",
    title: "Workout Tracker",
    desc: "52-week training program with guided workouts and logging.",
    icon: "🏋️",
    href: "/apps/fitness/",
    enabled: true,
  },
  {
    id: "travel-planner",
    title: "Travel Planner",
    desc: "Plan trips with itineraries, packing lists, and budgets.",
    icon: "✈️",
    href: "/apps/travel-planner/",
    enabled: true,
  },
  {
    id: "tickets",
    title: "Home Tickets",
    desc: "Household task tracker — Kanban board, recurring tasks, and two-person collaboration.",
    icon: "🏠",
    href: "/apps/tickets/",
    enabled: true,
  },
  {
    id: "osrs",
    title: "OSRS Max Tracker",
    desc: "Track The BrummJob's journey to the max cape.",
    icon: "⚔️",
    href: "/apps/osrs/",
    enabled: true,
  },
  {
    id: "homes",
    title: "NYC Home Search",
    desc: "Daily Zillow listings — Brooklyn, Queens, Manhattan under $650K.",
    icon: "🏠",
    href: "/apps/homes/",
    enabled: true,
  },
];
